USE ROLE avalanche_admin;
USE WAREHOUSE compute_wh;

CREATE CATALOG INTEGRATION IF NOT EXISTS blizzard_glue_catalog
  CATALOG_SOURCE = ICEBERG_REST
  TABLE_FORMAT = ICEBERG
  REST_CONFIG = (
    CATALOG_URI = 'https://glue.us-west-2.amazonaws.com/iceberg'
    CATALOG_API_TYPE = AWS_GLUE
    WAREHOUSE = ''
    ACCESS_DELEGATION_MODE = VENDED_CREDENTIALS
  )
  REST_AUTHENTICATION = (
    TYPE = SIGV4
    SIGV4_IAM_ROLE = ''
    SIGV4_SIGNING_REGION = 'us-west-2'
  )
  ENABLED = TRUE;

DESCRIBE CATALOG INTEGRATION blizzard_glue_catalog;

CREATE EXTERNAL VOLUME IF NOT EXISTS avalanche_s3_volume
  STORAGE_LOCATIONS = (
    (
      NAME = 'avalanche_s3'
      STORAGE_PROVIDER = 'S3'
      STORAGE_BASE_URL = ''
      STORAGE_AWS_ROLE_ARN = ''
      STORAGE_AWS_EXTERNAL_ID = ''
    )
  )
  ALLOW_WRITES = TRUE;
